### ISSUE TITLE
DAC8574 support?

### ISSUE THREAD

**Issue by doctea** [RobTillaart/DAC8571#3]
Hi!  I've been using your ADS1X15 and MCP23S17 libraries for a while now (many thanks!), and I have just started getting some DAC8574s ready on breadboard to expand my project.

I've forked this repo (https://github.com/doctea/DAC8574), and very quickly and roughly hacked in quad-channel support, since I can't find an already-existent implementation for the DAC8574 anywhere.

It basically works, although the output is very jittery compared to code that manually writes the values out to the DAC.

But before I get too far into modifying things myself, I wondered if you had any plans to make a library for the DAC8574, or any tips on the best way to modify one of your existing libraries to do the job please?

**Comment by RobTillaart** [comment]
Thanks for the question

I have to check the datasheet and find time to work on it. Do you need it on short term?

**Comment by doctea** [comment]
Thanks for your swift reply!  I am in no urgent hurry, and can make do with my current bodges for a while :).  I am also planning to make a small sponsorship donation since I have had so much good use from your libraries so far.

**Comment by RobTillaart** [comment]
Thanks, appreciated.

Had a quick look at your updated fork of the repo and it looks good (at least no very strange things).

Will setup a repository this week, and publish at platformIO and in the library manager.

**Comment by RobTillaart** [comment]
created placeholder - https://github.com/RobTillaart/DAC8574

**Comment by RobTillaart** [comment]
@doctea 

Created a develop branch with first version, build is running.
1.  get all examples compiling with channel 0 only
2. review all code against the datasheet
3. test with hardware, that's where I need your help
4. extend and stabilize 
5. documentation 
6. etc

----

update: 1 done in develop branch.
update: 2 done in develop branch

**Comment by RobTillaart** [comment]
@doctea 

A first review of the code with datasheet is done.
Can you give the develop branch a try with your hardware?
Please test the examples with channel 0, and if that works try to use channel 1,2, and 3

Thanks!

**Comment by RobTillaart** [comment]
@doctea 

documentation is updated to remove references of DAC8571 and better match the DAC8574.

**Comment by RobTillaart** [comment]
@doctea 

Updated the error handling, if build succeeds I will merge the develop branch,

Please open new issues under the DAC8574 branch, or just to let me know your test results.

**Comment by RobTillaart** [comment]
@doctea 

published library on platformIO and in the library manager, should be available within 24 hrs.

**Comment by doctea** [comment]
Wow, that was quick!  Thanks @RobTillaart!  I'll try and look at this tonight and test it on my hardware.  Much appreciated!

**Comment by RobTillaart** [comment]
@doctea 
Thanks for the donation!
